import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import AppLayout from "@/components/ui/AppLayout";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Experalia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <AppLayout>{children} </AppLayout>
      </body>
    </html>
  );
}
